version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
  - master

environment:
  matrix:
    - nodejs_version: "10.6.0"
    - nodejs_version: "8.11.1"

image: Visual Studio 2017

clone_folder: c:\azure-functions-nodejs-worker

install:
- ps: Install-Product node $env:nodejs_version x86

cache: 'node_modules'

build_script:
- ps: |
      $buildNumber = 0      
      if($env:APPVEYOR_REPO_TAG -eq "true") {
       $buildNumber = ""
       Write-Host “Found git tag. Not setting package suffix"
      } 
      else {
       $buildNumber = "-$env:APPVEYOR_BUILD_NUMBER"
       Write-Host “git tag not found. Setting package suffix to '$buildNumber'"
      }     
      .\package.ps1 -buildNumber $buildNumber

after_build:
- ps: |
      .\setup-e2e-tests.ps1
      $proc = start-process -filepath "c:\projects\azure-functions-nodejs-worker\Azure.Functions.Cli\func.exe" -WorkingDirectory "c:\projects\azure-functions-nodejs-worker\test\end-to-end\testFunctionApp" -ArgumentList "host start" -PassThru
      # wait for host to start
      Start-Sleep -s 30

test_script:
- npm run test
- ps: | 
      .\run-e2e-tests.ps1

artifacts:
- path: 'pkg/*.nupkg'

on_finish:
- ps: |
      Stop-Process -Id $proc.Id -Erroraction Ignore