version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
  - master

environment:
  matrix:
    - nodejs_version: "10.0.0"
    - nodejs_version: "8.11.1"

image: Visual Studio 2017
clone_folder: c:\azure-functions-nodejs-worker
install:
- ps: Install-Product node $env:nodejs_version x86
cache: 'node_modules'
build_script:
- ps: |
      $buildNumber = 0      
      if($env:APPVEYOR_REPO_TAG -eq "true") {
       $buildNumber = ""
       Write-Host “Found git tag. Not setting package suffix"
      } 
      else {
       $buildNumber = "-$env:APPVEYOR_BUILD_NUMBER"
       Write-Host “git tag not found. Setting package suffix to '$buildNumber'"
      }     
      .\package.ps1 -buildNumber $buildNumber
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
test_script:
- npm run test
artifacts:
- path: 'pkg/*.nupkg'