variables: {
  NODE_10: '10.x',
  NODE_12: '12.x',
  NODE_14: '14.x'
}

pr: none
trigger: none

strategy:
    maxParallel: 1
    # Node 8 is only supported in v2 compat mode and Mac isn't worth the extra build time unless we can get better parallel job support
    matrix:
      UBUNTU_NODE10:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_10)
      UBUNTU_NODE12:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_12)
      UBUNTU_NODE14:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_14)
      WINDOWS_NODE10:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_10)
      WINDOWS_NODE12:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_12)
      WINDOWS_NODE14:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_14)
pool:
    vmImage: $(IMAGE_TYPE)
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'
  - script: npm ci
    displayName: 'npm ci'
  - script: npm run build
    displayName: 'npm run build'
  - pwsh: |
      .\setup-e2e-tests.ps1 -UseCoreToolsBuildFromIntegrationTests
    displayName: 'Setup e2e tests'
  - powershell: |
      .\run-e2e-tests.ps1
    displayName: 'Run e2e tests'
    env:
      AzureWebJobsStorage: $(AzureWebJobsStorage)
      AzureWebJobsEventHubSender: $(AzureWebJobsEventHubSender)
      AzureWebJobsCosmosDBConnectionString: $(AzureWebJobsCosmosDBConnectionString)
      FUNCTIONS_WORKER_RUNTIME: 'node'
      nodeVersion: $(NODE_VERSION)
  - task: PublishTestResults@2
    displayName: 'Publish E2E Test Results'
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      testRunTitle: '$(Agent.JobName)'
