variables: {
  WORKER_VERSION: '2.1.2',
  NODE_12: '12.x'
}
name: $(WORKER_VERSION)-$(Date:yyyyMMdd)$(Rev:.r)

jobs:
- job: E2ETests
  strategy:
    maxParallel: 1
    matrix:
      NODE10:
        NODE_VERSION: $(NODE_12)
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js for test'
  - script: npm install
    displayName: 'npm install'
  - script: npm run build
    displayName: 'npm run build'
  - powershell: |
      .\run-e2e-tests.ps1
    env:
      AzureWebJobsStorage: $(AzureWebJobsStorage)
      AzureWebJobsEventHubSender: $(AzureWebJobsEventHubSender)
      AzureWebJobsCosmosDBConnectionString: $(AzureWebJobsCosmosDBConnectionString)
      FUNCTIONS_WORKER_RUNTIME: 'node'
      FunctionAppUrl: $(FunctionAppUrl)
      languageWorkers:node:workerDirectory: $(System.DefaultWorkingDirectory)
    continueOnError: true
  - task: CopyFiles@2
    inputs:
     SourceFolder: '$(System.DefaultWorkingDirectory)/test/testResults'
     Contents: '*.trx'
     TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
     ArtifactName: 'testResults'
     publishLocation: 'Container'