variables: {
  NODE_8: '8.x', # Can still be used if `FUNCTIONS_V2_COMPATIBILITY_MODE` is set
  NODE_10: '10.x',
  NODE_12: '12.x',
  NODE_14: '14.x'
}

pr:
  branches:
    include:
      - v2.x

trigger:
- v2.x

jobs:
- job: UnitTests
  strategy:
    matrix:
      UBUNTU_NODE8:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_8)
      UBUNTU_NODE10:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_10)
      UBUNTU_NODE12:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_12)
      UBUNTU_NODE14:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_14)
      WINDOWS_NODE8:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_8)
      WINDOWS_NODE10:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_10)
      WINDOWS_NODE12:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_12)
      WINDOWS_NODE14:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_14)
      MAC_NODE8:
        IMAGE_TYPE: 'macOS-latest'
        NODE_VERSION: $(NODE_8)
      MAC_NODE10:
        IMAGE_TYPE: 'macOS-latest'
        NODE_VERSION: $(NODE_10)
      MAC_NODE12:
        IMAGE_TYPE: 'macOS-latest'
        NODE_VERSION: $(NODE_12)
      MAC_NODE14:
        IMAGE_TYPE: 'macOS-latest'
        NODE_VERSION: $(NODE_14)
  pool:
    vmImage: $(IMAGE_TYPE)
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'
  - script: npm ci
    displayName: 'npm ci'
  - script: npm run build
    displayName: 'npm run build'
  - script: npm run lint
    condition: not(eq(variables['NODE_VERSION'], variables['NODE_8'])) # eslint doesn't support Node 8
    displayName: 'npm run lint'
  - script: npm test
    displayName: 'Run unit tests'
  - task: PublishTestResults@2
    displayName: 'Publish Unit Test Results'
    inputs:
      testResultsFiles: 'test/unit-test-results.xml'
      testRunTitle: '$(Agent.JobName)'
    condition: succeededOrFailed()

- job: E2ETests
  strategy:
    maxParallel: 1
    # Node 8 is only supported in v2 compat mode and Mac isn't worth the extra build time unless we can get better parallel job support
    matrix:
      UBUNTU_NODE10:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_10)
      UBUNTU_NODE12:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_12)
      UBUNTU_NODE14:
        IMAGE_TYPE: 'ubuntu-latest'
        NODE_VERSION: $(NODE_14)
      WINDOWS_NODE10:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_10)
      WINDOWS_NODE12:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_12)
      WINDOWS_NODE14:
        IMAGE_TYPE: 'windows-latest'
        NODE_VERSION: $(NODE_14)
  pool:
    vmImage: $(IMAGE_TYPE)
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'
  - script: npm ci
    displayName: 'npm ci'
  - script: npm run build
    displayName: 'npm run build'
  - pwsh: |
      .\setup-e2e-tests.ps1
    displayName: 'Setup e2e tests'
  - powershell: |
      .\run-e2e-tests.ps1
    displayName: 'Run e2e tests'
    env:
      AzureWebJobsStorage: $(AzureWebJobsStorage)
      AzureWebJobsEventHubSender: $(AzureWebJobsEventHubSender)
      AzureWebJobsCosmosDBConnectionString: $(AzureWebJobsCosmosDBConnectionString)
      FUNCTIONS_WORKER_RUNTIME: 'node'
      languageWorkers:node:workerDirectory: $(System.DefaultWorkingDirectory)
      nodeVersion: $(NODE_VERSION)
  - task: PublishTestResults@2
    displayName: 'Publish E2E Test Results'
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      testRunTitle: '$(Agent.JobName)'
